downloader/urls.py
from django.urls import path
from django.conf.urls import include, url

from . import views

app_name = 'downloader'

urlpatterns = [
    url(r'^add/direct/', views.startRequest, name='add-direct'),
    url(r'^add/', views.AddView.as_view(), name='add'),
    url(r'^downloads/', views.DownloadsView.as_view(), name='downloads'),
]

otrtools/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView
from filebrowser.sites import site

import downloader.urls

urlpatterns = [
    path('admin/filebrowser/', site.urls),
    path('grappelli/', include('grappelli.urls')),
    path('admin/', admin.site.urls, name='admin'),
    path('search/', include('searcher.urls'), name='searcher'),
    path('download/', include('downloader.urls'), name='downloader'),
    path('', RedirectView.as_view(pattern_name='searcher:main'), name='main'),
]

searcher/urls.py
from django.urls import path
from django.conf.urls import include, url
from django.views.generic import RedirectView

from . import views

app_name = 'searcher'

urlpatterns = [
    path('movies/', views.MovieView.as_view(), name='movies'),
    path('movies/<str:name>/', views.MovieView.as_view(), name='movies-search'),
    path('series/', views.SeriesView.as_view(), name='series'),
    path('series/add/', views.SeriesAddView.as_view(), name='series-add'),
    path('series/<int:series>/<int:season>/', views.SeriesView.as_view(), name='series'),
    path('cutlist/<str:file>/', views.cutlist, name='cutlist'),
    path('cutlist_test/', views.cutlist_test, name='cutlist-test'),
    path('clearCache/', views.clearCache, name='clear-cache'),
    path('', RedirectView.as_view(pattern_name=f'{app_name}:movies', permanent=False), name='main'),
]

searcher/models.py
from django.db import models


# Create your models here.
# class Title(models.Model):
#     title = models.CharField(max_length=200)
#     length = models.DateTime()

class Series(models.Model):
    url = models.URLField(max_length=300)
    website = models.CharField(max_length=2)
    series = models.CharField(max_length=200)
    german = models.BooleanField()
    otrNameFormat = models.CharField(max_length=200, blank=True)
    numSeasons = models.IntegerField(default=1)
    hidden = models.BooleanField(default=False)

    def get_season_range(self):
        return range(1, self.numSeasons + 1)

    def get_url(self, season=1):
        return self.url.format(season=season)

    def __str__(self):
        return self.series

searcher/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit

from .models import Series


class MovieIndexForm(forms.Form):
    query = forms.CharField(
        label="Query to otrkeyfinder.de",
        max_length=200,
        widget=forms.TextInput(attrs={'required': False}))

    min_duration = forms.IntegerField(initial=80, min_value=0, max_value=500, label="Minimum duration")
    max_page = forms.IntegerField(initial=20, min_value=1, max_value=50, label="Maximum pages")
    start_page = forms.IntegerField(initial=1, min_value=0, max_value=30, label="Start page")

    @property
    def helper(self):
        helper = FormHelper()
        helper.form_method = 'post'
        helper.add_input(Submit('submit', 'Search'))
        return helper


class SimpleSearchForm(MovieIndexForm):
    # class Meta:
    #     fields = ['query']
    def __init__(self, *args, **kwargs):
        initial = kwargs.get('initial', {})
        initial['max_page'] = 10
        kwargs['initial'] = initial
        super().__init__(*args, **kwargs)
        self.fields['max_page'].widget = forms.HiddenInput()
        self.fields['min_duration'].widget = forms.HiddenInput()
        self.fields['start_page'].widget = forms.HiddenInput()


class SeriesAddForm(forms.ModelForm):
    class Meta:
        model = Series
        fields = ['url', 'website', 'series', 'numSeasons', 'german', 'otrNameFormat']
        labels = {
            'url': "URL to episode list",
            'website': "Website",
            'series': "Name of the series",
            'numSeasons': "Number of seasons",
            'german': "Use German titles? (only for serienjunkies.de)",
            'otrNameFormat': "Custom Format to search for files",
        }
        widgets = {
            'website': forms.Select(choices=(
                ('IM', 'IMDB'),
                ('SJ', 'Serienjunkies'),
            )),
            'otrNameFormat': forms.TextInput(
                attrs={'placeholder': "{OTRserise} S{season:02d}E{episode:02d} {OTRtitle}"})
        }

    @property
    def helper(self):
        helper = FormHelper()
        helper.form_method = 'post'
        helper.add_input(Submit('submit', 'Add'))
        return helper

searcher/views.py
# coding: utf-8
from django.contrib import messages
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, JsonResponse, HttpResponseBadRequest, HttpResponseRedirect
from django.urls import reverse
from django.views.generic.base import View, TemplateView
from django.views.generic.edit import CreateView, FormView
import urllib.parse, requests
from itertools import groupby
from datetime import timedelta
from operator import itemgetter, attrgetter

from multiprocessing.dummy import Pool
from itertools import chain, repeat

from otrtools.views import BaseView
from .otrkeyfinder import Title, getTitles, refreshKeys, toOTRName
from .episode_lists import get_episode_list
from .forms import MovieIndexForm, SeriesAddForm
from .models import Series

sortkeyfn = lambda t: t['title']


def group_titles(titles):
    res = []
    num = 0;
    for k, values in groupby(titles, sortkeyfn):
        # print(k)
        values = list(values)
        for i in range(0, len(values)):
            values[i]['num'] = i
        isSimilarDecoded = any(x['isSimilarDecoded'] or x['isDecoded'] for x in values)
        seconds = [x['length'].seconds for x in values]
        item_count = len(seconds)
        time = timedelta(seconds=sum(seconds) / item_count)

        res.append(Title(k, time, values, isSimilarDecoded, num))  # {'title': k, 'length': time, 'items':list(values)})
    return res


class MovieView(BaseView, FormView):
    template_name = 'searcher/movies.html'
    form_class = MovieIndexForm

    def form_valid(self, form, **kwargs):
        query = form.cleaned_data.get("query")
        min_duration = form.cleaned_data.get('min_duration')
        max_page = form.cleaned_data.get("max_page")
        start_page = form.cleaned_data.get("start_page")

        refreshKeys()
        titles = getTitles(
            search=query,
            page_start=start_page,
            page_num=max_page,
            min_dur=min_duration)
        grouped = group_titles(titles)
        ctx = self.get_context_data(form=form, **kwargs)
        ctx['new_titles'] = list(filter(lambda t: not t.isSimilarDecoded, grouped))
        ctx['old_titles'] = list(filter(lambda t: t.isSimilarDecoded, grouped))

        return render(self.request, 'searcher/movies.html', ctx)

    def get(self, *args, **kwargs):
        if 'name' in kwargs:
            form = MovieIndexForm(data={
                'query': kwargs.get('name'),
                'min_duration': 50,
                'max_page': 5,
                'start_page': 1,
            })
            if form.is_valid():
                return MovieView.form_valid(self, form, **kwargs)
            else:
                return HttpResponseBadRequest("Invalid parameter!")
        else:
            return super().get(*args, **kwargs)

    def get_context_data(self, **kwargs):
        ctx = super(FormView, self).get_context_data(**kwargs)
        ctx.update(super(MovieView, self).get_context_data(**kwargs))
        return ctx
    # def request()
    # grouped = []
    # if request.method == 'POST':
    #     form = MovieIndexForm(request.POST)
    #     if form.is_valid():
    #
    # else:
    #     form = MovieIndexForm()

class SeriesAddView(BaseView, FormView):
    template_name = 'searcher/series-add.html'
    form_class = SeriesAddForm

    def form_valid(self, form, **kwargs):
        # url = form.cleaned_data.get("url")
        # website = form.cleaned_data.get('website')
        # series = form.cleaned_data.get("series")
        # german = form.cleaned_data.get("german")
        # otrNameFormat = form.cleaned_data.get("otrNameFormat")
        form.save()
        form.clean()

        # ctx = self.get_context_data(**kwargs)
        # ctx.update({
        #     'form': form
        # })
        messages.info(self.request, 'Added series')
        return HttpResponseRedirect(reverse('searcher:series')) #render(self.request, 'searcher/series.html', ctx)

    def get_context_data(self, **kwargs):
        ctx = super(FormView, self).get_context_data(**kwargs)
        ctx.update(super(SeriesAddView, self).get_context_data(**kwargs))
        return ctx


class SeriesView(BaseView, TemplateView):
    template_name = 'searcher/series.html'

    def getEpisodeTitles(self, url, series, episode):
        # title = toOTRName(episode['title'])
        # query = toOTRName(series)
        results = getTitles(search=episode['search'], page_start=0, page_num=1, min_dur=20)
        episode['otr'] = results
        episode['decoded'] = any(r for r in results if r['isDecoded'])
        episode['url'] = urllib.parse.urljoin(url, episode['url'])
        return episode


    def get_season_episodes(self, series, season):
        url = series.url.format(season=season)
        episodelist = get_episode_list(website=series.website, url=url, series=series.series, german=series.german,
                                       otrNameFormat=series.otrNameFormat)
        refreshKeys()
        episodes = []
        with Pool(4) as p:
            episodes = list(p.starmap(self.getEpisodeTitles, zip(
                repeat(url),
                repeat(series),
                episodelist
            )))
        return episodes

    def get_context_data(self, **kwargs):
        ctx = super(TemplateView, self).get_context_data(**kwargs)
        ctx.update(super(SeriesView, self).get_context_data(**kwargs))

        ctx['serieslist'] = []
        for s in Series.objects.filter(hidden=False):
            ctx['serieslist'].append((s, s._meta))

        if all(x in self.kwargs for x in ['series', 'season']):
            series = get_object_or_404(Series, pk=self.kwargs['series'])
            season = self.kwargs['season']

            if season <= 0:
                episodes = []
                for i in series.get_season_range():
                    episodes.extend(self.get_season_episodes(series, i))
            else:
                episodes = self.get_season_episodes(series, season)

            ctx['episodes'] = episodes

        return ctx


def cutlist_test(request):
    return render(request, 'searcher/cutlists.html', {})


def cutlist(request, file):
    # json = {'items': [{'id': 322848,
    #    'name': 'Lethal Weapon  Best Buds',
    #    'airDate': '2016-10-05T20:00:00+02:00',
    #    'uploadDate': '2016-10-08T22:25:06+02:00',
    #    'otrkey': 'Lethal_Weapon__Best_Buds_16.10.05_20-00_uswnyw_60_TVOON_DE.mpg.HQ.avi',
    #    'comment': 'inkl. Vorschau, cut with Super OTR (Super OTR 0.9.6.0b79)',
    #    'suggestedName': 'Lethal Weapon - S01E03 - Best Buds',
    #    'channel': 'uswnyw',
    #    'author': 'Hummel',
    #    'rating': {'avg': '0.00', 'n': 0, 'author': 5},
    #    'hits': 2,
    #    'duration': '00:43:20',
    #    'quality': 'hq',
    #    'cutCount': 6,
    #    'errors': {'start': False,
    #     'end': False,
    #     'video': False,
    #     'audio': False,
    #     'other': False,
    #     'epg': False,
    #     'epgDesc': None,
    #     'otherDesc': None},
    #    '_my': {'canRate': True}},
    #   {'id': 324225,
    #    'name': 'Lethal Weapon  Best Buds',
    #    'airDate': '2016-10-05T20:00:00+02:00',
    #    'uploadDate': '2016-10-06T23:32:15+02:00',
    #    'otrkey': 'Lethal_Weapon__Best_Buds_16.10.05_20-00_uswnyw_60_TVOON_DE.mpg.HQ.avi',
    #    'comment': None,
    #    'suggestedName': 'Lethal Weapon - S01E03 - Best Buds - HQ',
    #    'channel': 'uswnyw',
    #    'author': 'katteld1',
    #    'rating': {'avg': '5.00', 'n': 3, 'author': 5},
    #    'hits': 46,
    #    'duration': '00:42:56',
    #    'quality': 'hq',
    #    'cutCount': 6,
    #    'errors': {'start': False,
    #     'end': False,
    #     'video': False,
    #     'audio': False,
    #     'other': False,
    #     'epg': False,
    #     'epgDesc': None,
    #     'otherDesc': None},
    #    '_my': {'canRate': True}}],
    #    'hasMore': False,
    #    'currentPage': 0}
    data = '{"conds":[{"query":"%s","field":"name"}],"isOrConnection":false,"sortBy":"datebroadcast","isAsc":true,"page":0}' % file
    # print(data)
    resp = requests.post('http://www.cutlist.at/api/search-by', data=data)
    json = resp.json()
    # print(json)
    items = [dict(item) for item in json['items']]
    try:
        items = sorted(items, key=itemgetter('hits'), reverse=True)
    except:
        pass
    try:
        items = sorted(items, key=lambda item: item['rating']['avg'] * min(5, item['rating']['ratings']), reverse=True)
    except:
        pass
    # print(items)
    # return JsonResponse(resp.json())
    return JsonResponse({'items': items})


def clearCache(request):
    getTitles.cache_clear()
    refreshKeys()
    return JsonResponse({'success': True})

searcher/templates/searcher/base.html
<!doctype html>
<html lang="en">
<head> {% load bootstrap4 %}
  {% block header %}
  {% endblock %}
</head>
<body class="bg-dark text-white">
  {% block navbar %}
  {% endblock %}
  </br>
  {% bootstrap_messages %}
  {% block content %}
  {% endblock %}

{% include 'searcher/modules/footer.html' %}
</body>
</html>

searcher/templates/searcher/cutlists.html
<html>
<head>
  <script src="https://code.jquery.com/jquery-3.3.1.min.js" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
  <base target="_blank">
</head>
<body>
  <div class="container">
    <table class="table table-striped" id="cutlist-table">

    </table>
    <script type="text/javascript">
      $.getJSON("{% url 'searcher:cutlist' 'test' %}", function(data) {
        items = ['<thead><th>Rating</th><th>Downloads</th><th>Description</th><th>Sug. Name</th></thead>']
        $.each(data.items, function (key, item) {
          row = '<tr>';
          row += '<td><span style="color: blue;">' + item.rating.n + "x " + item.rating.avg + '</span></td>';
          row += '<td>' + item.hits + '</td>';
          row += '<td>' + item.comment + '</td>';
          row += '<td>' + item.suggestedName + '</td>';
          row += '<td><a href="http://www.cutlist.at/getfile.php?id=' + item.id + '">Link</a></td>';
          row += '</tr>';
          items.push(row);
        });
        console.log(items);
        // for (var item in data) {
        //   if (data.hasOwnProperty(item)) {
        //
        //   }
        // }
        $('#cutlist-table').html(items.join(""));
      });
    </script>
  </div>
</body>
</html>

searcher/templates/searcher/movies.html
{% extends 'searcher/base.html' %}

{% load crispy_forms_tags %}

{% block header %}
  {% include 'searcher/modules/header.html' with title="Movies" %}
{% endblock %}

{% block navbar %}
  {% include 'searcher/modules/navbar.html' with page="movies" %}
{% endblock %}
{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-md-10 offset-md-1">
      <h1>Movies</h1>
        <form action="{% url 'searcher:movies' %}" method="post">
            {% csrf_token %}
            {{ form.query|as_crispy_field }}
            <div class="row">
              <div class="col-4">
                {{ form.min_duration|as_crispy_field }}
              </div>
              <div class="col-4">
                {{ form.max_page|as_crispy_field }}
              </div>
              <div class="col-4">
                {{ form.start_page|as_crispy_field }}
              </div>
            </div>
            <button type="submit" class="btn btn-success">Search</button>
            <button type="button" id="clearCacheBtn" class="btn btn-warning" onclick="javascript:clearCache();">Clear cache</button>
        </form>
      </div>
    </div>
    {% if new_titles %}
    <br />
    <div class="row">
      <div class="col-md-12">
        <h2>Results</h2>
        {% include "searcher/modules/movie_titles.html" with titles=new_titles prefix="undecoded_" %}
      </div>
    </div>
    {% endif %}
    {% if old_titles %}
    <br />
    <div class="row">
      <div class="col-md-12">
        <h2>Decoded Results</h2>
        {% include "searcher/modules/movie_titles.html" with titles=old_titles prefix="decoded_"%}
      </div>
    </div>
    {% endif %}
  </div>
    
<script type="text/javascript">
function clearCache() {
  $.getJSON('{% url 'searcher:clear-cache' %}', function(data) {
    if (data.success == true) {
      $('#clearCacheBtn').attr({'class': 'btn btn-info'}).html("Cleared").prop('disabled', true);
    }
  });
}
</script>
{% endblock %}

searcher/templates/searcher/series-add.html
{% extends 'searcher/base.html' %}

{% load crispy_forms_tags %}
{% load admin_urls %}
{% load icons %}

{% block header %}
  {% include 'searcher/modules/header.html' with title="Series" %}
    <style>
    .btn-season {
        margin: 2px 0;
    }
    </style>
{% endblock %}

{% block navbar %}
  {% include 'searcher/modules/navbar.html' with page="series" %}
{% endblock %}
{% block content %}
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <h1>Series</h1>
    </div>
    <div class="col-lg-6">
      <h3>Add a new series</h3>
      {% crispy form %}
    </div>
  </div>
</div>
{% endblock %}

searcher/templates/searcher/series.html
{% extends 'searcher/base.html' %}

{% load crispy_forms_tags %}
{% load admin_urls %}
{% load icons %}

{% block header %}
  {% include 'searcher/modules/header.html' with title="Series" %}
    <style>
    .btn-season {
        margin: 2px 0;
    }
    </style>
{% endblock %}

{% block navbar %}
  {% include 'searcher/modules/navbar.html' with page="series" %}
{% endblock %}
{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-12">
        <h1>Series</h1>
      </div>
      <div class="col-lg-10">
        <h3>Select a series</h3>
        <table class="table">
          <tbody>
          <tr><td colspan="3">
              <span class="text-success"> {% icon "add" %} <a class="text-success" href="{% url 'searcher:series-add' %}">Add a Series</a></span>
          </td></tr>
          {% for s, meta in serieslist %}
          <tr>
            <td><a target="_blank" href="{{ s.get_url }}">{{s.series}}</a></td>
            <td>
              <a
                  class="btn btn-secondary btn-sm btn-season" type="button"
                  href="{% url 'searcher:series' series=s.pk season=0 %}"
                  data-toggle="tooltip" data-placement="top" title="All Seasons"
              >All</a>
              {% for i in s.get_season_range %}
                  <a
                      class="btn btn-secondary btn-sm btn-season " type="button"
                      href="{% url 'searcher:series' series=s.pk season=i %}"
                      data-toggle="tooltip" data-placement="top" title="Season {{ i }}"
                  >{{ i }}</a>
              {% endfor %}
            </td>
{#            <td><select name="">#}
{#              <option value="0">Select Episode</option>#}
{#              <option value="-1" onclick="location.href='{% url 'searcher:series' series=s.pk season=0 %}';">All</option>#}
{#              {% for i in s.get_season_range %}#}
{#              <option value="{{ e }}" onclick="location.href='{% url 'searcher:series' series=s.pk season=i %}';">{{ i }}</option>#}
{#              {% endfor %}#}
{#            </select></td>#}
            <td><a
              class="btn btn-success btn-sm" type="button"
              href="{% url meta|admin_urlname:'change' s.pk %}"
              data-toggle="tooltip" data-placement="top" title="Edit"
              >{% icon 'edit' %}</a></td>
          </tr>
          {% empty %}
          <tr>
            <td>No series available.</td>
          </tr>
          {% endfor %}
          </tbody>
        </table>
      </div>
      <div class="col-lg-12 episode-list">
        {% if episodes %}
        <h3>Episodes</h3>
        {% endif %}
        <table class="table table-striped table-dark">
        <tr><td>
          {% for e in episodes %}
            <div class="row row-episode text-light">
              <div class="col-sm-3 col-md-2 col-lg-2"><span style="font-size: 110%; font-weight: bold;{% if e.decoded %}text-decoration-line: line-through;{% endif %}">
                  <a target="_blank" href="{{ e.url }}">{{ e.season }}x{{ e.episode }} {{ e.title }}</a>
              </span></div>
              {% with e.otr as titles %}
              <div class="col-11 offset-1 col-md-10 offset-md-0 col-lg-10">
                <!--<table class="table table-striped text-light">-->
                {% if titles %}
                    <!-- include items.html-->
                    {% include "searcher/modules/items.html" with items=titles num=forloop.counter destName=e.destName %}
                    <!-- end include items.html-->
                {% else %}
                  <div class="row"><div class="col-12">No files found for this episode. <a target="_blank" href="https://otrkeyfinder.com/en/?search={{ e.search }}&order=date-name">Search</a> and <a target="_blank" href="{% url 'downloader:add' %}?dest={{ e.destName }}">add</a> manually.</div></div>
                {% endif %}
                <!--</table>-->
              </div>
              {% endwith %}
            </div>
          {% endfor %}
        </td></tr>
        </table>
      </div>
    </div>
  </div>
{% endblock %}