downloader/urls.py
from django.urls import path
from django.conf.urls import include, url

from . import views

app_name = 'downloader'

urlpatterns = [
    url(r'^add/direct/', views.startRequest, name='add-direct'),
    url(r'^add/', views.AddView.as_view(), name='add'),
    url(r'^downloads/', views.DownloadsView.as_view(), name='downloads'),
]

otrtools/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView
from filebrowser.sites import site

import downloader.urls

urlpatterns = [
    path('admin/filebrowser/', site.urls),
    path('grappelli/', include('grappelli.urls')),
    path('admin/', admin.site.urls, name='admin'),
    path('search/', include('searcher.urls'), name='searcher'),
    path('download/', include('downloader.urls'), name='downloader'),
    path('', RedirectView.as_view(pattern_name='searcher:main'), name='main'),
]

searcher/urls.py
from django.urls import path
from django.conf.urls import include, url
from django.views.generic import RedirectView

from . import views

app_name = 'searcher'

urlpatterns = [
    path('movies/', views.MovieView.as_view(), name='movies'),
    path('movies/<str:name>/', views.MovieView.as_view(), name='movies-search'),
    path('series/', views.SeriesView.as_view(), name='series'),
    path('series/add/', views.SeriesAddView.as_view(), name='series-add'),
    path('series/<int:series>/<int:season>/', views.SeriesView.as_view(), name='series'),
    path('cutlist/<str:file>/', views.cutlist, name='cutlist'),
    path('cutlist_test/', views.cutlist_test, name='cutlist-test'),
    path('clearCache/', views.clearCache, name='clear-cache'),
    path('', RedirectView.as_view(pattern_name=f'{app_name}:movies', permanent=False), name='main'),
]

searcher/models.py
from django.db import models


# Create your models here.
# class Title(models.Model):
#     title = models.CharField(max_length=200)
#     length = models.DateTime()

class Series(models.Model):
    url = models.URLField(max_length=300)
    website = models.CharField(max_length=2)
    series = models.CharField(max_length=200)
    german = models.BooleanField()
    otrNameFormat = models.CharField(max_length=200, blank=True)
    numSeasons = models.IntegerField(default=1)
    hidden = models.BooleanField(default=False)

    def get_season_range(self):
        return range(1, self.numSeasons + 1)

    def get_url(self, season=1):
        return self.url.format(season=season)

    def __str__(self):
        return self.series

searcher/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit

from .models import Series


class MovieIndexForm(forms.Form):
    query = forms.CharField(
        label="Query to otrkeyfinder.de",
        max_length=200,
        widget=forms.TextInput(attrs={'required': False}))

    min_duration = forms.IntegerField(initial=80, min_value=0, max_value=500, label="Minimum duration")
    max_page = forms.IntegerField(initial=20, min_value=1, max_value=50, label="Maximum pages")
    start_page = forms.IntegerField(initial=1, min_value=0, max_value=30, label="Start page")

    @property
    def helper(self):
        helper = FormHelper()
        helper.form_method = 'post'
        helper.add_input(Submit('submit', 'Search'))
        return helper


class SimpleSearchForm(MovieIndexForm):
    # class Meta:
    #     fields = ['query']
    def __init__(self, *args, **kwargs):
        initial = kwargs.get('initial', {})
        initial['max_page'] = 10
        kwargs['initial'] = initial
        super().__init__(*args, **kwargs)
        self.fields['max_page'].widget = forms.HiddenInput()
        self.fields['min_duration'].widget = forms.HiddenInput()
        self.fields['start_page'].widget = forms.HiddenInput()


class SeriesAddForm(forms.ModelForm):
    class Meta:
        model = Series
        fields = ['url', 'website', 'series', 'numSeasons', 'german', 'otrNameFormat']
        labels = {
            'url': "URL to episode list",
            'website': "Website",
            'series': "Name of the series",
            'numSeasons': "Number of seasons",
            'german': "Use German titles? (only for serienjunkies.de)",
            'otrNameFormat': "Custom Format to search for files",
        }
        widgets = {
            'website': forms.Select(choices=(
                ('IM', 'IMDB'),
                ('SJ', 'Serienjunkies'),
            )),
            'otrNameFormat': forms.TextInput(
                attrs={'placeholder': "{OTRserise} S{season:02d}E{episode:02d} {OTRtitle}"})
        }

    @property
    def helper(self):
        helper = FormHelper()
        helper.form_method = 'post'
        helper.add_input(Submit('submit', 'Add'))
        return helper

searcher/views.py
# coding: utf-8
from django.contrib import messages
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, JsonResponse, HttpResponseBadRequest, HttpResponseRedirect
from django.urls import reverse
from django.views.generic.base import View, TemplateView
from django.views.generic.edit import CreateView, FormView
import urllib.parse, requests
from itertools import groupby
from datetime import timedelta
from operator import itemgetter, attrgetter

from multiprocessing.dummy import Pool
from itertools import chain, repeat

from otrtools.views import BaseView
from .otrkeyfinder import Title, getTitles, refreshKeys, toOTRName
from .episode_lists import get_episode_list
from .forms import MovieIndexForm, SeriesAddForm
from .models import Series

sortkeyfn = lambda t: t['title']


def group_titles(titles):
    res = []
    num = 0;
    for k, values in groupby(titles, sortkeyfn):
        # print(k)
        values = list(values)
        for i in range(0, len(values)):
            values[i]['num'] = i
        isSimilarDecoded = any(x['isSimilarDecoded'] or x['isDecoded'] for x in values)
        seconds = [x['length'].seconds for x in values]
        item_count = len(seconds)
        time = timedelta(seconds=sum(seconds) / item_count)

        res.append(Title(k, time, values, isSimilarDecoded, num))  # {'title': k, 'length': time, 'items':list(values)})
    return res


class MovieView(BaseView, FormView):
    template_name = 'searcher/movies.html'
    form_class = MovieIndexForm

    def form_valid(self, form, **kwargs):
        query = form.cleaned_data.get("query")
        min_duration = form.cleaned_data.get('min_duration')
        max_page = form.cleaned_data.get("max_page")
        start_page = form.cleaned_data.get("start_page")

        refreshKeys()
        titles = getTitles(
            search=query,
            page_start=start_page,
            page_num=max_page,
            min_dur=min_duration)
        grouped = group_titles(titles)
        ctx = self.get_context_data(form=form, **kwargs)
        ctx['new_titles'] = list(filter(lambda t: not t.isSimilarDecoded, grouped))
        ctx['old_titles'] = list(filter(lambda t: t.isSimilarDecoded, grouped))

        return render(self.request, 'searcher/movies.html', ctx)

    def get(self, *args, **kwargs):
        if 'name' in kwargs:
            form = MovieIndexForm(data={
                'query': kwargs.get('name'),
                'min_duration': 50,
                'max_page': 5,
                'start_page': 1,
            })
            if form.is_valid():
                return MovieView.form_valid(self, form, **kwargs)
            else:
                return HttpResponseBadRequest("Invalid parameter!")
        else:
            return super().get(*args, **kwargs)

    def get_context_data(self, **kwargs):
        ctx = super(FormView, self).get_context_data(**kwargs)
        ctx.update(super(MovieView, self).get_context_data(**kwargs))
        return ctx
    # def request()
    # grouped = []
    # if request.method == 'POST':
    #     form = MovieIndexForm(request.POST)
    #     if form.is_valid():
    #
    # else:
    #     form = MovieIndexForm()

class SeriesAddView(BaseView, FormView):
    template_name = 'searcher/series-add.html'
    form_class = SeriesAddForm

    def form_valid(self, form, **kwargs):
        # url = form.cleaned_data.get("url")
        # website = form.cleaned_data.get('website')
        # series = form.cleaned_data.get("series")
        # german = form.cleaned_data.get("german")
        # otrNameFormat = form.cleaned_data.get("otrNameFormat")
        form.save()
        form.clean()

        # ctx = self.get_context_data(**kwargs)
        # ctx.update({
        #     'form': form
        # })
        messages.info(self.request, 'Added series')
        return HttpResponseRedirect(reverse('searcher:series')) #render(self.request, 'searcher/series.html', ctx)

    def get_context_data(self, **kwargs):
        ctx = super(FormView, self).get_context_data(**kwargs)
        ctx.update(super(SeriesAddView, self).get_context_data(**kwargs))
        return ctx


class SeriesView(BaseView, TemplateView):
    template_name = 'searcher/series.html'

    def getEpisodeTitles(self, url, series, episode):
        # title = toOTRName(episode['title'])
        # query = toOTRName(series)
        results = getTitles(search=episode['search'], page_start=0, page_num=1, min_dur=20)
        episode['otr'] = results
        episode['decoded'] = any(r for r in results if r['isDecoded'])
        episode['url'] = urllib.parse.urljoin(url, episode['url'])
        return episode


    def get_season_episodes(self, series, season):
        url = series.url.format(season=season)
        episodelist = get_episode_list(website=series.website, url=url, series=series.series, german=series.german,
                                       otrNameFormat=series.otrNameFormat)
        refreshKeys()
        episodes = []
        with Pool(4) as p:
            episodes = list(p.starmap(self.getEpisodeTitles, zip(
                repeat(url),
                repeat(series),
                episodelist
            )))
        return episodes

    def get_context_data(self, **kwargs):
        ctx = super(TemplateView, self).get_context_data(**kwargs)
        ctx.update(super(SeriesView, self).get_context_data(**kwargs))

        ctx['serieslist'] = []
        for s in Series.objects.filter(hidden=False):
            ctx['serieslist'].append((s, s._meta))

        if all(x in self.kwargs for x in ['series', 'season']):
            series = get_object_or_404(Series, pk=self.kwargs['series'])
            season = self.kwargs['season']

            if season <= 0:
                episodes = []
                for i in series.get_season_range():
                    episodes.extend(self.get_season_episodes(series, i))
            else:
                episodes = self.get_season_episodes(series, season)

            ctx['episodes'] = episodes

        return ctx


def cutlist_test(request):
    return render(request, 'searcher/cutlists.html', {})


def cutlist(request, file):
    # json = {'items': [{'id': 322848,
    #    'name': 'Lethal Weapon  Best Buds',
    #    'airDate': '2016-10-05T20:00:00+02:00',
    #    'uploadDate': '2016-10-08T22:25:06+02:00',
    #    'otrkey': 'Lethal_Weapon__Best_Buds_16.10.05_20-00_uswnyw_60_TVOON_DE.mpg.HQ.avi',
    #    'comment': 'inkl. Vorschau, cut with Super OTR (Super OTR 0.9.6.0b79)',
    #    'suggestedName': 'Lethal Weapon - S01E03 - Best Buds',
    #    'channel': 'uswnyw',
    #    'author': 'Hummel',
    #    'rating': {'avg': '0.00', 'n': 0, 'author': 5},
    #    'hits': 2,
    #    'duration': '00:43:20',
    #    'quality': 'hq',
    #    'cutCount': 6,
    #    'errors': {'start': False,
    #     'end': False,
    #     'video': False,
    #     'audio': False,
    #     'other': False,
    #     'epg': False,
    #     'epgDesc': None,
    #     'otherDesc': None},
    #    '_my': {'canRate': True}},
    #   {'id': 324225,
    #    'name': 'Lethal Weapon  Best Buds',
    #    'airDate': '2016-10-05T20:00:00+02:00',
    #    'uploadDate': '2016-10-06T23:32:15+02:00',
    #    'otrkey': 'Lethal_Weapon__Best_Buds_16.10.05_20-00_uswnyw_60_TVOON_DE.mpg.HQ.avi',
    #    'comment': None,
    #    'suggestedName': 'Lethal Weapon - S01E03 - Best Buds - HQ',
    #    'channel': 'uswnyw',
    #    'author': 'katteld1',
    #    'rating': {'avg': '5.00', 'n': 3, 'author': 5},
    #    'hits': 46,
    #    'duration': '00:42:56',
    #    'quality': 'hq',
    #    'cutCount': 6,
    #    'errors': {'start': False,
    #     'end': False,
    #     'video': False,
    #     'audio': False,
    #     'other': False,
    #     'epg': False,
    #     'epgDesc': None,
    #     'otherDesc': None},
    #    '_my': {'canRate': True}}],
    #    'hasMore': False,
    #    'currentPage': 0}
    data = '{"conds":[{"query":"%s","field":"name"}],"isOrConnection":false,"sortBy":"datebroadcast","isAsc":true,"page":0}' % file
    # print(data)
    resp = requests.post('http://www.cutlist.at/api/search-by', data=data)
    json = resp.json()
    # print(json)
    items = [dict(item) for item in json['items']]
    try:
        items = sorted(items, key=itemgetter('hits'), reverse=True)
    except:
        pass
    try:
        items = sorted(items, key=lambda item: item['rating']['avg'] * min(5, item['rating']['ratings']), reverse=True)
    except:
        pass
    # print(items)
    # return JsonResponse(resp.json())
    return JsonResponse({'items': items})


def clearCache(request):
    getTitles.cache_clear()
    refreshKeys()
    return JsonResponse({'success': True})

searcher/templates/searcher/modules/footer.html
{% load static %}
<script src="{% static 'searcher/js/popper.min.js' %}" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="{% static 'searcher/js/bootstrap.min.js' %}" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
<script type="text/javascript">
  function loadCutlists(file_url, destName, video_url, mirror_name, table_id) {
    $(table_id).html("<tr><td>Loading..</td></tr>");
    $.getJSON(file_url, function(data) {
      //console.log(data.items)
      found_cutlists = false;
      let hasComment = false;
      $.each(data.items, function (key, item) {
          if (item.comment) {
              hasComment = true;
          }
      });
      let item = '';
      if (hasComment) {
          item = '<thead>' +
          '<th style="width: 37.5%">Rating/<br />Downloads<br />Sug. Name</th>' +
          '<th style="width: 37.5%">Comment</th>' +
          '<th style="width: 25%">Actions</th></thead>';
      } else {
          item = '<thead>' +
          '<th style="width: 70%">Rating/<br />Downloads<br />Sug. Name</th>' +
          '<th style="width: 30%">Actions</th></thead>';
      }
      let itemdiv = $($.parseHTML(item));
      $.each(data.items, function (key, item) {
        cutlist_url = 'http://www.cutlist.at/getfile.php?id=' + item.id;
        let row = $('<tr></tr>');
        itemdiv.append(row);
        let td = $('<td></td>');
        row.append(td);
        //row = '<tr>';
        //row += '<td>';
        td.append($('<div><span class="text-info">' + item.rating.ratings + "x " + item.rating.avg + '</span></div>'));;
        td.append($('<div>' + item.hits + '</div>'));;
        td.append($('<br />'));;
        td.append($('<div style="word-wrap: break-word">' + item.suggestedName + '</div>'));;
        //row += '</td>';
        if (hasComment) {
            row.append($('<td style="word-wrap: break-word">' + item.comment + '</td>'));;
        }
        //row += '<td>';
        td = $('<td></td>');
        row.append(td);
        let linksdiv = $('<div style="margin-bottom: 5px;"></div>');
        td.append(linksdiv);
        let a = $('<a target="_blank" class="btn btn-success"></a>');
        linksdiv.append(a);
        let params = {
            "video": video_url,
            "cutlist": cutlist_url,
            "dest": destName
        };
        a.attr({
            'onclick': 'startDownload(this, ' + JSON.stringify(params) + ');',
            'title': 'Uses ' + mirror_name
        });
        a.text('Add');
            //row += '<div style="margin-bottom: 5px;"><a target="_blank" class="btn btn-success" onclick="startDownload(this,`
              //+ "{\n"
              //+ "video: " + video + ","
              //+ "cutlist": cutlist,
              //  "dest": dest,
              //}+ decodeURI(video_url) + ","
              //+ cutlist_url + "','"
              //+ destName
              //+ '\');" title="Uses ' + mirror_name + '">Add</a></div>';
        linksdiv = $('<div style="margin-bottom: 5px;"></div>');
        td.append(linksdiv);
        a = $('<a target="_blank" class="text-information"></a>');
        linksdiv.append(a);
        a.attr({
            'title': 'Uses ' + mirror_name,
            'href': '{% url 'downloader:add' %}?' + $.param(params)
        });
        a.text('Add Manually');
        td.append($('<div><a target="_blank" href="' + cutlist_url + '">Link</a></div>'));;
        //row += '</td>';
        //row += '</tr>';
        //items.push(row);
        found_cutlists = true;
      });
      //console.log(items);
      // for (var item in data) {
      //   if (data.hasOwnProperty(item)) {
      //
      //   }
      // }
      if (found_cutlists === true) {
          $(table_id).html(itemdiv);
      } else {
          let tr = $('<tr></tr>');
          let td = $('<td></td>');
          tr.append(td);
          let linksdiv = $('<div style="margin-bottom: 5px;">');
          td.append('No cutlist found. ');
          td.append(linksdiv);
          let a = $('<a></a>');
          linksdiv.append(a);
          let params = {
            "video": video_url,
            "dest": destName
        };
        a.attr({
            'target':  "_blank",
            'class':   "btn btn-info",
            'onclick': 'startDownload(this, ' + JSON.stringify(params) + ');',
            'title':   'Uses ' + mirror_name
        });
        a.text('Add without cutting');
        $(table_id).html(tr);
      }
    });
  }
  var btn = {};
function startDownload(button, params) {
  btn['btn'] = $(button);
  let url = '{% url 'downloader:add-direct' %}'; // + video + '/' + cutlist + '/' + dest + '/';
  $.post(url, params, function(data) {
    if (data.success == true) {
        $(button).attr({'class': 'btn btn-info'}).html("Added").prop('disabled', true);
    } else {
        $(button).attr({'class': 'btn btn-warning'}).html("Failed :( Try again?");
    }
  });
}
</script>

searcher/templates/searcher/modules/header.html
<meta charset="utf-8">{% load static %}
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<script src="{% static 'searcher/js/jquery-3.4.1.min.js' %}"></script>
<link rel="stylesheet" href="{% static 'searcher/css/bootstrap.min.css' %}" >
<link rel="stylesheet" href="{% static 'searcher/css/font-awesome.css' %}" >
<title>{{ title }}</title>
<style media="screen">
.asteriskField {
    display: none;
}
html {
  position: relative;
  min-height: 100%;
}
body {
  /* Margin bottom by footer height */
  margin-bottom: 60px;
}
body > .container {
  padding: 60px 15px 0;
}
/*.textinput, .numberinput {*/
.form-control {
    background-color: #555;
    color: #FFF;
}

.footer {
  position: absolute;
  bottom: 0;
  width: 100%;
  /* Set the fixed height of the footer here */
  height: 60px;
  line-height: 60px; /* Vertically center the text there */
  background-color: #f5f5f5;
}
.footer > .container {
  padding-right: 15px;
  padding-left: 15px;
}

.row-title, .row-episode {
    border: #888888 1px solid;
    padding: 5px 0px 10px 0px;
}

</style>

searcher/templates/searcher/modules/items.html
{% load item_tags %}

{% for item in items %}
<div class="row movie-item" style="margin-bottom: 10px;"><div class="col-12">

    <div class="row{% if not forloop.first %} collapse collapse-{{ num }}{% endif %}" style="padding: 5px 0px 15px 0px;">
    {#<tr{% if not forloop.first %} class="collapse collapse-{{ num }}"{% endif %}>#}
      <div class="col-9 col-lg-7"><a target="_blank" href="https://otrkeyfinder.com/en/?search={{ item.file }}&order=date-name"><span class="badge badge-{{ item.format|format2label }}">{{ item.format }}</span> {{ item.title }}</a></div>
      <div class="col-3 col-lg-5">{{ item.length }}</div>
    </div>
    <div class="row{% if not forloop.first %} collapse collapse-{{ num }}{% endif %}">
    {#<tr{% if not forloop.first %} class="collapse collapse-{{ num }}"{% endif %}>#}
      <div class="col-md-3 col-lg-3 movie-links">
        <table class="table table-striped">
          {% for m in item.mirrors %}
          <tr>
            <td><a target="_blank" href="{{ m.link }}">{{ m.name }}</a></td>
          </tr>
          {% empty %}
              No mirrors found! :(
          {% endfor %}
        </table>
      </div>
      <div class="col-md-9 col-lg-9 movie-cutlists">
        {% concat "cutlist-table-" prefix "-" num "-" forloop.counter as cutlist_table_id %}
        <table style="table-layout: fixed; width: 100%" class="table text-light bg-dark" id="{{ cutlist_table_id }}">
            <tr><td><a href="javascript:{% cutlist_call item cutlist_table_id destName True %}" class="text-success">Load cutlists</a></td></tr>
        </table>
        <script>
          {% if not forloop.first %}
            $('.collapse-{{ num }}:first').on('show.bs.collapse', function() {
              $('#more-{{ num }}').remove();

              {% cutlist_call item cutlist_table_id destName %};
            });
          {% endif %}
        </script>

      </div>
    </div>
    {% if forloop.first and items|length > 1 %}
    <div class="row" id="more-{{ num }}">
      <div class="col-12"><a class="btn btn-primary" data-toggle="collapse" data-target=".collapse-{{ num }}" role="button" aria-expanded="false" aria-controls="collapse-{{ num }}"> ({{ items|length|add:"-1" }}) More..</a></div>
    </div>
    {% endif %}
</div></div>
{% endfor %}

searcher/templates/searcher/modules/movie_titles.html
<table class="table table-striped table-dark">
<tr><td>
{% for t in titles %}
<div class="row row-title">
    <div class="col-sm-3 col-lg-2">
        <table class="table table-dark text-light bg-dark">
            <tr><td><a target="_blank" href="https://otrkeyfinder.com/en/?search={{ t.title }} {{search}}&order=date-name"><span style="{% if t.isDecoded %}text-decoration-line: line-through;{% elif t.isSimilarDecoded %}color: #777777;{% endif %}">{{ t.title }}</span></a></td></tr>
            <tr><td>{{ t.length }}</td></tr>
            <tr><td>{{ t.item_count }}</td></tr>
            <tr><td><a target="_blank" href="https://www.imdb.com/find?q={{ t.title }}&s=all">IMDB</a></td></tr>
            <tr><td><a target="_blank" href="https://www.youtube.com/results?search_query={{ t.title }} Trailer">Youtube Trailer</a></td></tr>
            <tr><td><a target="_blank" href="{% url 'searcher:movies-search' name=t.title %}">Similar Movies</a></td></tr>
        </table>
    </div>
    <div class="col-11 offset-1 col-sm-9 offset-sm-0 col-lg-10">
{#        <table class="table table-striped text-light bg-dark">#}
        <!-- include items.html-->
        {% include "searcher/modules/items.html" with items=t.items num=forloop.counter prefix=prefix %}
        <!-- end include items.html-->
{#      </table>#}
    </div>
</div>
{% endfor %}
</td></tr>
</table>

searcher/templates/searcher/modules/navbar.html
{% load crispy_forms_tags %}
<header>
  <nav class="navbar navbar-expand-md navbar-dark">
    <a class="navbar-brand" href="{% if page == "movies" %}#{% else %}{% url 'searcher:movies' %}{% endif %}">OTR Tools</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item{% if page == "movies" %} active{% endif %}">
          <a class="nav-link" href="{% url 'searcher:movies' %}">Movies <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item{% if page == "series" %} active{% endif %}">
          <a class="nav-link" href="{% url 'searcher:series' %}">Series</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Tools
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item{% if page == "add" %} active{% endif %}" href="{% url 'downloader:add' %}">Add Manually</a>
            <a class="dropdown-item{% if page == "downloads" %} active{% endif %}" href="{% url 'downloader:downloads' %}">Show Downloads</a>
            <a class="dropdown-item" href="#">Show logs..</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{% url 'admin:index' %}">Administration</a>
          </div>
        </li>
      </ul>
      {% comment %}
      <form class="form-inline my-2 my-md-0" action="{% url 'searcher:movies' %}" method="post">
        {% csrf_token %}
        <!-- <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search"> -->

        <!-- <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button> -->
      </form>
      {% endcomment %}
      <form class="form-inline my-2 my-md-0" action="{% url 'searcher:movies' %}" method="post">
          {% csrf_token %}
          <input name="{{nav_form.query.name}}" class="form-control textinput mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          {{ nav_form.min_duration|as_crispy_field }}
          {{ nav_form.max_page|as_crispy_field }}
          {{ nav_form.start_page|as_crispy_field }}
          <button type="submit" class="btn btn-success">Search</button>
      </form>
    </div>
  </nav>
</header>